openapi: 3.0.0
info:
  title: Music Player
  description: API สำหรับโปรเจค Music Player
  version: 0.1
servers:
  - url: http://localhost:3000/
    description: My Localhost
paths:
  /users:
    # GET All Users
    get:
      summary: Returns a list of all users.
      description: |
        แสดงรายชื่อผู้ใช้ทั้งหมดในรูปแบบอาเรย์ของออบเจ็กต์<br>
        ผู้ใช้แต่ละคนจะประกอบด้วยข้อมูล เช่น ID, ชื่อ, อีเมล เป็นต้น
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
    # POST new user
    post:
      summary: Creates a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_user'   # component for create
      responses:
        '201':
          description: User is created.
        '409':
          description: User ID already exists.
        '500':
          description: Server error.

  /users/{id}:
    # GET User by ID
    get:
      summary: Returns the specified user.
      description: |
        แสดงข้อมูลผู้ใช้ในรูปแบบอาเรย์ของออบเจ็กต์
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        '200':
          description: A JSON object representing the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '404':
          description: A user with the specified ID was not found.
        '500':
          description: Server error.

components:
  schemas:
    user:
      type: object
      properties:
        user_id:
          type: string
        user_name:
          type: string
        user_email:
          type: string
        user_password:
          type: string
        created_at:
          type: string
          format: date-time
    new_user:
      type: object
      properties:
        user_name:
          type: string
        user_email:
          type: string
        user_password:
          type: string
